11 
    de.renew.gui.CPNDrawing 10 
        de.renew.gui.PlaceFigure "attributes" "attributes" 2 "FigureWithID" "Int" 1 "targetLocation" "String" "target" 597 178 20 20 NULL  
        de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 2 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 711 178 20 20 NULL REF 1  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 5 "LineWidth" "Int" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3 "TextAlignment" "Int" 0 "FillColor" "Color" 255 199 158 255 593 155 "text" "Droid Sans" 2 14 0 NULL NULL  
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5 2 617 188 712 188 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 2   
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 6 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 621 196 "connection text" "SansSerif" 0 12 0 REF 4 
            CH.ifa.draw.standard.OffsetLocator 6 15 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 7 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 547 203 "inscription" "SansSerif" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator -28 22 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 8 "TextAlignment" "Int" 1 "TextColor" "Color" 0 0 0 204 "FillColor" "Color" 255 199 158 255 702 159 "name" "SansSerif" 1 12 0 REF 2 
            CH.ifa.draw.standard.OffsetLocator 0 -22 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.DeclarationFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 9 "TextAlignment" "Int" 0 "FillColor" "Color" 255 199 158 255 753 186 "d=1;" "SansSerif" 0 12 0 NULL NULL 1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 10 "TextAlignment" "Int" 1 "TextColor" "Color" 0 0 255 255 "FillColor" "Color" 255 199 158 255 532 176 "comment" "SansSerif" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator -46 -5 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   4  
        CH.ifa.draw.contrib.TriangleFigure "attributes" "attributes" 1 "FigureWithID" "Int" 12 547 330 127 62 5  NULL  0 0 2560 1410 