11
    de.renew.gui.CPNDrawing 26 
        CH.ifa.draw.figures.RectangleFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1 56 273 102 69  
        CH.ifa.draw.figures.RoundRectangleFigure "attributes" "attributes" 1 "FigureWithID" "Int" 2 261 238 121 70 8 8  
        CH.ifa.draw.figures.EllipseFigure "attributes" "attributes" 1 "FigureWithID" "Int" 3 495 191 81 38  
        CH.ifa.draw.figures.PieFigure "attributes" "attributes" 1 "FigureWithID" "Int" 4 682 279 116 102 180.0 90.0  
        CH.ifa.draw.contrib.DiamondFigure "attributes" "attributes" 2 "FigureWithID" "Int" 5 "targetLocation" "String" "yy" 837 108 130 73  
        CH.ifa.draw.figures.LineFigure "attributes" "attributes" 1 "FigureWithID" "Int" 6 2 516 524 714 591 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  NULL "CH.ifa.draw.figures.ArrowTip"  
        CH.ifa.draw.figures.ElbowConnection "attributes" "attributes" 1 "FigureWithID" "Int" 7 4 382 281 532 281 532 330 683 330 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopRoundRectangleConnector REF 2  
            CH.ifa.draw.figures.ChopPieConnector REF 4   
        CH.ifa.draw.figures.PolyLineFigure "attributes" "attributes" 1 "FigureWithID" "Int" 8 53 611 441 616 442 618 442 621 442 625 443 629 443 635 444 640 445 647 445 653 446 661 446 668 447 675 447 683 447 691 447 701 447 710 448 719 449 729 449 737 450 747 451 757 452 767 454 777 456 786 458 794 461 802 463 810 466 817 469 823 473 829 478 834 482 839 488 844 493 848 498 852 502 856 505 858 509 860 513 862 517 864 520 866 524 867 528 867 531 868 534 869 537 870 539 870 542 872 545 873 548 874 551 874 552 875 553 NULL NULL "CH.ifa.draw.figures.ArrowTip"  
        CH.ifa.draw.contrib.PolygonFigure "attributes" "attributes" 1 "FigureWithID" "Int" 9 10 304 583 347 585 402 513 399 464 375 444 300 428 310 468 194 465 253 550 322 160  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 10 "TextAlignment" "Int" 0 "FillColor" "Color" 255 199 158 255 497 738 "sss" "SansSerif" 0 12 0 NULL NULL  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 11 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 732 323 "aa" "SansSerif" 0 12 0 REF 4 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 14 247 706 24 16 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 15 262 759 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 16 2 271 760 260 722 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 20  
            CH.ifa.draw.standard.ChopBoxConnector REF 19   
        de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 17 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 320 725 20 20 NULL REF 20  
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 18 617 704 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 19 2 637 714 688 715 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 26  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 20 688 708 24 16 NULL    REF 31 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 21 2 712 716 783 721 NULL
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip"
            CH.ifa.draw.standard.ChopBoxConnector REF 31
            CH.ifa.draw.figures.ChopEllipseConnector
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 22 782 711 20 20 NULL    REF 36
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 23 2 802 722 831 725 NULL
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 36  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 24 831 719 24 16 NULL    REF 41 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 25 2 855 728 942 738 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 41  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 26 941 728 20 20 NULL    REF 46 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 27 2 961 740 1099 769 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 46  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 28 1099 764 24 16 NULL    REF 51 NULL  0 17 2560 1423 